### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by PandKent** [ZxIce/FairyGUIToLua#2]
您好 我是新手使用者 请问这个插件应该如何使用 或者我应该在Fgui编辑器内做什么设置么？

**Comment by ZxIce** [comment]
[插件教程地址](https://www.fairygui.com/docs/guide/editor/plugin.html)

**Comment by vkensou** [comment]
同问。我导入了插件，也设置了gen_lua属性。但是点生成没有导出lua文件

**Comment by vkensou** [comment]
找到了，原来是生成到 UIProject目录下了

**Comment by ZxIce** [comment]
插件使用教程见链接
